### ISSUE TITLE
[Request] Availability Within HTML Files?

### ISSUE THREAD

**Issue by austin-guevara** [diemogebhardt/atom-language-ampscript#1]
Hey there! I'm not sure if this is even possible, but could highlighting and other functionality be enabled for HTML files?

**Comment by diemogebhardt** [comment]
@austin-guevara 

Hey Austin, is this still something you'd need? Sorry for getting back to you this late!

It's definitely possible but I'd have to have another look into it. It's been a while... ;)

As you are working at Salesforce: do you know if there are any plans of replacing AMPscript with something else in the near future?

**Comment by diemogebhardt** [comment]
@austin-guevara 

Probably too late but the feature is implemented.

Check out v0.6.0! :)

**Comment by austin-guevara** [comment]
@diemogebhardt – this is a phenomenal enhancement! Thank you for your work on this project! Should it apply syntax highlight of AMPScript to .html files, or add syntax highlighting of HTML to .amp/.ampscript files?

As to answer your previous question, I‘m not a part of the product team, so I don‘t know what the definite answer would be. But safe to say, it’ll be around for a while.

**Comment by austin-guevara** [comment]
And I’ll add to that, nevermind! I see from looking through the package files that it’s '.html.ampscript' – thank you!

**Comment by diemogebhardt** [comment]
@austin-guevara 

I am glad it is of use to anyone else other than just myself, you are welcome! :)

**Comment by austin-guevara** [comment]
@diemogebhardt – I can’t believe more people aren’t crazy about this! It’s extremely valuable. Thanks for taking the time to implement my request.

I’d also love to eventually convert [this brackets extension](https://github.com/ccarswell/ampscript-beautifier) to an Atom package.
